name: conduit-throttle
version: '0.3.1.0'
synopsis: Throttle Conduit Producers
description: This packages is based on the throttle-io-stream package
             and provides functionality for throttling Conduit
             producers according to a provided configuration.
category: Data
author: Moritz Schulte
maintainer: mtesseract@silverratio.net
copyright: (c) 2017 Moritz Schulte
license: BSD3
github: mtesseract/conduit-throttle
ghc-options:
- -Wall
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- conduit
- conduit-combinators
- conduit-extra
- stm-chans
- stm
- resourcet
- async
- unliftio >= 0.2.1.0
- unliftio-core
- throttle-io-stream
- resourcet
- monad-control
library:
  source-dirs: src
  exposed-modules:
  - Data.Conduit.Throttle
  - Data.Conduit.Throttle.MBC
tests:
  conduit-test:
    main: Tests.hs
    source-dirs: tests
    default-extensions:
    - OverloadedStrings
    ghc-options:
    - -Wall
    - -fno-warn-type-defaults
    dependencies:
    - base >=4.7 && <5
    - HUnit
    - test-framework
    - test-framework-hunit
    - conduit-throttle
    - throttle-io-stream
    - stm-conduit
